
language: node_js

node_js:
  - 11

cache: npm

install: 
  npm install

before_script:
  - Mongoose.connect(process.env.DB_CONNECTION,
    { useNewUrlParser: true,useUnifiedTopology: true,useCreateIndex: true,useFindAndModify: false},)

script:
  - npm test
after_success: npm run coverage
